substitutions:
    _BRANCH: develop # default branch to build value

steps:
## Start CloudDatastore and CloudPubSub emulator
### Datastore on :5545
- name: 'gcr.io/cloud-builders/docker'
  args: ['run','-d', '-p','5545:5545', '--name', 'my-datastore', '-e', 'CLOUDSDK_CORE_PROJECT=test', 'gcr.io/cloud-builders/gcloud', 'beta', 'emulators','datastore','start', '--host-port=0.0.0.0:5545']
- name: 'alpine'
  args: ['sleep', '4']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--network','host', 'appropriate/curl', '--retry', '4', '--retry-connrefused', '--retry-delay', '3', 'http://localhost:5545']

### Pubsub on :8085
- name: 'gcr.io/cloud-builders/docker'
  id: 'pubsub'
  args: ['run', '-d', '-p', '8085:8085', '--name', 'my-pubsub', '-e', 'CLOUDSDK_CORE_PROJECT=test', 'gcr.io/cloud-builders/gcloud', 'beta', 'emulators','pubsub','start', '--host-port=0.0.0.0:8085']
  waitFor: ['-']
- name: 'alpine'
  args: ['sleep', '5']
- name: 'gcr.io/cloud-builders/docker'
  args: ['logs', 'my-pubsub']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--network','host', 'appropriate/curl', '--retry', '4', '--retry-connrefused', '--retry-delay', '3', 'http://localhost:8085']

## Prepare source code
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://$PROJECT_ID/credentials/builder/key.enc', './key.enc']
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://$PROJECT_ID/credentials/builder/known_hosts', './known_hosts']
  waitFor: ['-']

## Prepare node_modules from cache
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://$PROJECT_ID/.cache/yarn-cache.tar.gz', '/workspace/yarn-cache.tar.gz']
  waitFor: ['-']
  id: fetch-cache
- name: 'mhart/alpine-node:10'
  args:
    - mkdir
    - -p
    - /workspace/.yarn-cache
  waitFor: ['-']
- name: 'mhart/alpine-node:10'
  args:
    - tar
    - -xf
    - /workspace/yarn-cache.tar.gz
    - -C
    - /workspace
  waitFor: ['fetch-cache']


- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - kms
    - decrypt
    - --ciphertext-file=key.enc
    - --plaintext-file=/root/.ssh/id_rsa
    - --location=global
    - --keyring=builder-git
    - --key=github
  volumes:
  - name: 'ssh'
    path: /root/.ssh


# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - git@github.com:catcatio/shio.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/cloud-builders/git'
  dir: shio
  args:
  - checkout
  - ${_BRANCH}

# ## Install dependencies
# #### YARN INSTALL
- name: 'mhart/alpine-node:10'
  dir: 'shio'
  env:
  - 'YARN_CACHE_FOLDER=/workspace/.yarn-cache'
  args:
  - yarn
  - install

- name: 'mhart/alpine-node:10'
  dir: 'shio'
  env:
  - 'YARN_CACHE_FOLDER=/workspace/.yarn-cache'
  args:
  - yarn
  - lerna
  - bootstrap


- name: 'gcr.io/cloud-builders/docker'
  id: 'foundation unit test'
  args:
  - run
  - --network
  - host
  - -w
  - /workspace/shio
  - -v
  - /workspace/shio:/workspace/shio
  - mhart/alpine-node:10
  - yarn
  - lerna
  - run
  - unit
  - --scope
  - "@shio-bot/foundation"

- name: 'gcr.io/cloud-builders/docker'
  id: 'foundation integration test'
  args:
  - run
  - --network
  - host
  - -w
  - /workspace/shio
  - -v
  - /workspace/shio:/workspace/shio
  - mhart/alpine-node:10
  - yarn
  - lerna
  - run
  - integration
  - --scope
  - "@shio-bot/foundation"


- name: 'gcr.io/cloud-builders/docker'
  id: 'fulfillment unit test'
  args:
  - run
  - --network
  - host
  - -w
  - /workspace/shio
  - -v
  - /workspace/shio:/workspace/shio
  - mhart/alpine-node:10
  - yarn
  - lerna
  - run
  - unit
  - --scope
  - "@shio-bot/fulfillment"


- name: 'gcr.io/cloud-builders/docker'
  id: 'fulfillment integration test'
  args:
  - run
  - --network
  - host
  - -w
  - /workspace/shio
  - -v
  - /workspace/shio:/workspace/shio
  - mhart/alpine-node:10
  - yarn
  - lerna
  - run
  - integration
  - --scope
  - "@shio-bot/fulfillment"